### ISSUE TITLE
SSL certificate of NFI FTP server (used for KNN data) is bad.

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/Biomass_validationKNN#2]
We need to change `httr::config` throughout this and other modules to be able to download KNN layers.
Solution:
- create a new module parameter that controls `httr::config(ssl_verify)` and wrap problematic prepInputs calls into `httr::with_config()`

**Comment by achubaty** [comment]
I have not dealt with this module since i am not using/testing this one -- but see similar fixes implemented on development branches of `Biomass_core`, `Biomass_borealDataPrep`, and `Biomass_speciesData`.

**Comment by CeresBarros** [comment]
Fixed in https://github.com/PredictiveEcology/Biomass_validationKNN/pull/3
