### ISSUE TITLE
Usage example - Package Installation 

### ISSUE THREAD

**Issue by viveksrivastava09** [PredictiveEcology/Biomass_validationKNN#6]
Require(paste0("PredictiveEcology/", "SpaDES.project@6d7de6ee12fc967c7c60de44f1aa3b04e6eeb5db"),
    require = FALSE, upgrade = FALSE, standAlone = TRUE)
#> Error in Require(paste0("PredictiveEcology/", "SpaDES.project@6d7de6ee12fc967c7c60de44f1aa3b04e6eeb5db"), : could not find function "Require"

paths <- list(inputPath = normPath(file.path(tempDir, "inputs")),
    cachePath = normPath(file.path(tempDir, "cache")), modulePath = normPath(file.path(tempDir,
        "modules")), outputPath = normPath(file.path(tempDir,
        "outputs")))
#> Error in normPath(file.path(tempDir, "inputs")): could not find function "normPath"

SpaDES.project::getModule(modulePath = paths$modulePath, c("PredictiveEcology/Biomass_core@master",
    "PredictiveEcology/Biomass_validationKNN@master"), overwrite = TRUE)
#> Error in SpaDES.project::getModule(modulePath = paths$modulePath, c("PredictiveEcology/Biomass_core@master", : object 'paths' not found

## make sure all necessary packages are installed:
outs <- SpaDES.project::packagesInModules(modulePath = paths$modulePath)
#> Error in dir(modulePath): object 'paths' not found
Require(c(unname(unlist(outs)), "PredictiveEcology/SpaDES.experiment@development",
    "future"), require = FALSE, standAlone = TRUE)
#> Error in Require(c(unname(unlist(outs)), "PredictiveEcology/SpaDES.experiment@development", : could not find function "Require"

## load necessary packages
Require(c("SpaDES.core", "LandR", "reproducible", "pemisc", "SpaDES.experiment",
    "future"), upgrade = FALSE, install = FALSE)
#> Error in Require(c("SpaDES.core", "LandR", "reproducible", "pemisc", "SpaDES.experiment", : could not find function "Require"

**Comment by CeresBarros** [comment]
You need to install the `Require` package to be able to use the `Require` function
See [this section](https://landr-manual.predictiveecology.org/landr-biomass_validationknn-module.html#bvalid-example-libs) of the Biomass_validationKNN manual
